sudo: required
services:
  - docker

env:
  global:
    - DATE=$(date '+%Y%m%d')
    - REPO="threathuntproj"
    - IMAGE_NAME="hunting-travistest"
    - JUPYTER_NB_PASS=""

before_script:

script:
  - echo ${DATE}
  - echo ${REPO}
  - echo ${IMAGE_NAME}
  - echo ${JUPYTER_NB_PASS}
  - docker build --build-arg JUPYTER_NB_PASS=$JUPYTER_NB_PASS -t $REPO/$IMAGE_NAME:latest -t $REPO/$IMAGE_NAME:$DATE .

after_script:
  - docker images
