sudo: required
services:
  - docker

global:
  - DATE=$(date '+%Y%m%d')
  - REPO="threathuntproj"
  - IMAGE_NAME="hunting-travistest"
  - JUPYTER_NB_PASS=""

script:
  - docker pull threathuntproj/hunting:latest || true
  - docker build --pull --cache-from threathuntproj/hunting:latest . 

after_script:
  - docker images
