sudo: required
services:
  - docker

global:
  - DATE=$(date '+%Y%m%d')
  - REPO="threathuntproj"
  - IMAGE_NAME="hunting-travistest"
  - JUPYTER_NB_PASS=""

script:
  - docker build . 

after_script:
  - docker images
