sudo: required
services:
  - docker

global:
  - DATE=$(date '+%Y%m%d')
  - REPO="threathuntproj"
  - IMAGE_NAME="hunting"
  - JUPYTER_NB_PASS=""

script:
  - docker build --build-arg JUPYTER_NB_PASS=$JUPYTER_NB_PASS -t $REPO/$IMAGE_NAME:latest

after_script:
  - docker images
