sudo: required
services:
  - docker

global:
  - DATE=$(date '+%Y%m%d')
  - REPO="threathuntproj"
  - IMAGE_NAME="hunting-travistest"
  - JUPYTER_NB_PASS=""

script:
  - docker build --build-arg JUPYTER_NB_PASS="$JUPYTER_NB_PASS" -t "$REPO"/"$IMAGE_NAME":latest -t "$REPO"/"$IMAGE_NAME":"$DATE"

after_script:
  - docker images
